{
 "title": "Gallifrey Rules",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Engine Initialized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Count",
     "query": "SELECT mean(\"count\") FROM \"engine_initialized\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Consumer lags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_topic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumer_partition_lags",
     "query": "SELECT mean(\"count\") FROM \"engine_initialized\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lag" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Event Timers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event_timer",
     "query": "SELECT mean(\"totalLag\") FROM \"consumer_lags\" WHERE $timeFilter GROUP BY time($__interval), \"group\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "event_timer",
     "query": "SELECT count(\"timerMs\") FROM \"action_timer\" WHERE $timeFilter GROUP BY time($__interval), \"action\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filter Timers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_filter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filter::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filter_timer",
     "query": "SELECT mean(\"totalLag\") FROM \"consumer_lags\" WHERE $timeFilter GROUP BY time($__interval), \"group\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filter Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_filter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "filter::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filter_timer",
     "query": "SELECT count(\"timerMs\") FROM \"action_timer\" WHERE $timeFilter GROUP BY time($__interval), \"action\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rule Timers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_rule",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rule::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rule_timer",
     "query": "SELECT mean(\"totalLag\") FROM \"consumer_lags\" WHERE $timeFilter GROUP BY time($__interval), \"group\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rule Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_rule",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rule::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rule_timer",
     "query": "SELECT count(\"timerMs\") FROM \"action_timer\" WHERE $timeFilter GROUP BY time($__interval), \"action\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Action Timers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "action_timer",
     "query": "SELECT mean(\"totalLag\") FROM \"consumer_lags\" WHERE $timeFilter GROUP BY time($__interval), \"group\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Action Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "action::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "action_timer",
     "query": "SELECT count(\"timerMs\") FROM \"action_timer\" WHERE $timeFilter GROUP BY time($__interval), \"action\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DataObject Timers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_data_object",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "rule::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_object_timer",
     "query": "SELECT mean(\"timerMs\") FROM \"data_object_timer\" WHERE $timeFilter GROUP BY time($__interval), \"data_object\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DataObject Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_data_object",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "data_object::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_object_timer",
     "query": "SELECT count(\"timerMs\") FROM \"action_timer\" WHERE $timeFilter GROUP BY time($__interval), \"action\"::tag fill(null)",
     "select": [
      [
       { "params": [ "timerMs" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}