name: Gallifrey Rules Tools Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: docker build . --file docker/tools.Dockerfile --tag gallifrey-rules-tools:$(date +%s)

    - name: Log in to GitHub Packages Docker registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag gallifrey-rules-tools:$(date +%s) ghcr.io/${{ github.repository_owner }}/gallifrey-rules-tools:latest
    - name: Push Docker image to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/gallifrey-rules-tools:latest
