name: On release build

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    #- name: Generate timestamp
    #  id: generate_timestamp
    #  run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build . --file docker/tools.Dockerfile --tag gallifrey-rules-tools:${{ github.event.release.tag_name }}

    - name: Log in to GitHub Packages Docker registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag gallifrey-rules-tools:${{ github.event.release.tag_name }} ghcr.io/${{ github.repository_owner }}/gallifrey-rules-tools:latest

    - name: Push Docker image to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/gallifrey-rules-tools:latest
